In [ ]:
import numpy as np      # ipynb - interactive python notebook
# it is writtten in c language and it is used as python . 
#  Since python has no array we use numpy library
# it is used for storing multidimensional data and can perform many operations and process data

# to add 5 marks for every marks
marks=np.array([80,90,78,88,98])
marks+5
marks/2
marks+5 # here we are just calculating and not printing


array([ 85,  95,  83,  93, 103])

In [ ]:
marks=marks-5  # here we store the value and printing
marks/2
print(marks)

[75 85 73 83 93]


In [ ]:
marks>78 # based on the output of last operations

array([False,  True, False,  True,  True])

Indexing

In [10]:
marks[2] 
print(marks[2])
print(marks[-2])

73
83


Traversing

In [11]:
for i in range(4):
    print(marks[i])

75
85
73
83


Slicing

In [12]:
marks[:2]

array([75, 85])

Multidimensional array(2d)

In [32]:
mark=np.array([
    [90,90,78],
    [78,56,98],
    [98,67,89]]
)
print(mark)

#indexing
print(mark[0][0])  # or 
print(mark[0,0])

# Slicing & indexing
print(mark[0:3])  
print(mark[0:2][0:2])


print(mark[1:,0])   # ------> 1 represent row and 0 represent column now 1: -> access 78,56,98  ,98,67,89 and in that 0 th column so output is 78,98
print(mark[1:][0])  #1: -> access 78,56,98  ,98,67,89  in that 0 th row so 78,56,98 is output

print(mark[0][0:2])
print(mark[0,0:2])

[[90 90 78]
 [78 56 98]
 [98 67 89]]
90
90
[[90 90 78]
 [78 56 98]
 [98 67 89]]
[[90 90 78]
 [78 56 98]]
[78 98]
[78 56 98]
[90 90]
[90 90]


In [31]:
print(mark[0][0:2])
print(mark[0,0:2])

[90 90]
[90 90]


Concatenation

In [39]:
b1=np.array([56,78,89])
b2=np.array([65,76,98])
comb=np.concatenate((b1,b2),axis=0)
comb

array([56, 78, 89, 65, 76, 98])

A combined dataset has 6 students. The academic team needs to divide into two groups

In [ ]:
print(np.split(comb,2))   # it always split into equal division

for i in np.split(comb,3): 
    print(i)

[array([56, 78, 89]), array([65, 76, 98])]
[56 78]
[89 65]
[76 98]


Axis

In [46]:
b1=np.array([
    [90,90,78],
    [78,56,98]])
b2=np.array([
    [66,70,88],
    [46,56,33]])

comb=np.concatenate((b1,b2),axis=0) # axis =0 represent rows(x axis)
# [[90 90 78]
#  [78 56 98]
#  [66 70 88]
#  [46 56 33]]
print(comb)

comb1=np.concatenate((b1,b2),axis=1) # axis =1 represent columns(y axis)
print(comb1)
# [[90 90 78 66 70 88]
#  [78 56 98 46 56 33]]

[[90 90 78]
 [78 56 98]
 [66 70 88]
 [46 56 33]]
[[90 90 78 66 70 88]
 [78 56 98 46 56 33]]


To search a value - where

In [ ]:
b1=np.array([
    [90,90,78],   
    [78,56,98]])
#Find where the mark is 78
print(np.where(b1==78))

# print marks greater than 78
print(np.where(b1>78))     # o/p: (array([0, 0, 1]), array([0, 1, 2])) --> 0,0=90   0,1=90    1,2=98

# instead of position print numbers
print(b1[np.where(b1>78)])  

(array([0, 1]), array([2, 0]))
(array([0, 0, 1]), array([0, 1, 2]))
[90 90 98]


To sort an array

In [ ]:
b1=np.array([
    [90,90,78],   
    [78,56,98]])

print(np.sort(b1))  # sort in ascending order by row

print(np.sort(b1)[::-1])  # to take the complete array and to sort it 

print(np.sort(b1,axis=0))  # to sort row wise

print(np.sort(b1,axis=1))  # to sort column wise

[[78 90 90]
 [56 78 98]]
[[56 78 98]
 [78 90 90]]
[[78 56 78]
 [90 90 98]]
[[78 90 90]
 [56 78 98]]


Data Vectorization
when we want to add +5 to all marks . when we do this operation without any loop it will applyy for all vectors

In [11]:
# In numpy when the array has different datatypes it coverts all the data to any one of the data type 

m=np.array([55,45,6.5])   # o/p : [55.  45.   6.5]
print(m)

m=np.array(["Ram",45])   # o/p : ['Ram' '45']
print(m)

m=np.array([True,"ram"])   # o/p : ['True' 'ram']     #how to handle 
print(m)
type(m[0])

[55.  45.   6.5]
['Ram' '45']
['True' 'ram']


numpy.str_

Reshape and resize changes the shape of the array:
1.Reshape - returns a new array with the specified shape
2.Resize - modifies the array in-place to match the specified shape.

A shallow copy creates a new array that refers to the same data as the original
array, while a deep copy creates a completely new array with its own data.
Modifying a deep copy does not affect the original array.


You can create a shallow copy of a NumPy array using the numpy.view() method. 
You can create a deep copy of a NumPy array using the numpy.copy() function

 numpy.split() function to split an array along a specified axis

numpy.argsort() function to get the indices of the sorted elements.  kind='quicksort' with
numpy.sort() to sort in descending order.

numpy.random.rand() generates random numbers from a uniform distribution in
the [0, 1) range.
numpy.random.randn() generates random numbers from a standard normal
(Gaussian) distribution with a mean of 0 and a standard deviation of 1


You can use numpy.loadtxt() to read data from a text file into a NumPy array.

numpy.save() saves data in a binary format, which is more efficient and
preserves data types and structures. numpy.savetxt() saves data as plain text,
which is human-readable but less efficient.

numpy.savez() allows you to save multiple NumPy arrays into a single
compressed archive. This is useful when you want to store several arrays in a
single file efficiently

You can use the numpy.genfromtxt() function and specify options like missing
values and dtype to handle missing data and data conversion issues when
reading files into NumPy arrays.